import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {spawn} from 'node:child_process';import http from 'node:http';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {pagesExportScript} from '../src/pages-export.mjs';
test('Actions static exporter uploads a checksum-bound artifact at its approved base path',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'actions-pages-'));let calls=0;
 const server=http.createServer(async(req,res)=>{calls++;const chunks=[];for await(const chunk of req)chunks.push(chunk);const bytes=Buffer.concat(chunks),bundle=JSON.parse(bytes);assert.equal(req.headers['x-checksum-sha256'],createHash('sha256').update(bytes).digest('hex'));assert.equal(bundle.format,'switchyard-static-v1');assert.equal(bundle.base_path,'/foo.js/');assert.equal(Buffer.from(bundle.files[0].body,'base64').toString(),'<h1>test</h1>');assert.equal(bundle.files[0].path,'/index.html');res.writeHead(200);res.end('{}');});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{await mkdir(path.join(root,'public'));await writeFile(path.join(root,'public/index.html'),'<h1>test</h1>');
 const output={directory:'public',base_path:'/foo.js/',limit:64*1024*1024,token:'disposable-static-grant',url:`http://127.0.0.1:${server.address().port}/upload`};
 const result=await new Promise(resolve=>{const child=spawn(process.execPath,['--input-type=module','-e',pagesExportScript.replace("workspace:'/workspace'","workspace:"+JSON.stringify(root))],{env:{...process.env,SWITCHYARD_STATIC_OUTPUT:JSON.stringify(output)}});let logs='';child.stdout.on('data',x=>logs+=x);child.stderr.on('data',x=>logs+=x);child.on('close',code=>resolve({code,logs}));});assert.equal(result.code,0,result.logs);assert.equal(calls,1);assert.ok(!result.logs.includes(output.token));
 }finally{await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});}
});

test('generated Actions exporter stays synchronized with the anchored Pages exporter',async()=>{const canonical=await readFile(new URL('../../pages/src/export.mjs',import.meta.url),'utf8');assert.ok(pagesExportScript.startsWith(canonical.replace('export async function exportStatic','async function exportStatic')));});
