// Package webassets contains the Nift-built product UI for binary-only releases.
package webassets

import "embed"

// Files is generated by the normal Nift/frontend build before Go compilation.
//
//go:embed *.html assets
var Files embed.FS
