import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {publishArtifact} from '../src/artifact.mjs';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
class Bucket{data=new Map();async put(key,body){if(this.data.has(key))return null;this.data.set(key,Buffer.from(body));return {etag:'ok'};}async get(key){const value=this.data.get(key);return value?{arrayBuffer:async()=>value,text:async()=>value.toString()}:null;}}
function fixture(){const body=Buffer.from('<h1>site</h1>'),bundle={format:'switchyard-static-v1',base_path:'/docs/',files:[{path:'/index.html',mime:'text/html',size:body.length,sha256:sha(body),body:body.toString('base64')}]},bytes=Buffer.from(JSON.stringify(bundle));return {bytes,args:{siteID:'site_test1',deploymentID:'deploy_test1',basePath:'/docs/',receipt:{name:'pages-static.bundle.json',sha256:sha(bytes),size:bytes.length,source_sha:'a'.repeat(40),job_id:'pages'}},bundle};}
test('concurrent artifact publication converges without overwrite',async()=>{const {bytes,args}=fixture(),bucket=new Bucket();const results=await Promise.all([publishArtifact(bucket,bytes,args),publishArtifact(bucket,bytes,args)]);assert.deepEqual(results[0],results[1]);assert.equal(bucket.data.size,2);assert.equal(results[0].source_sha,args.receipt.source_sha);});
test('artifact cannot redirect storage keys or forge payload checksum',async()=>{for(const change of [f=>f.path='/../secret',f=>f.sha256='b'.repeat(64),f=>f.size=999]){const {bundle,args}=fixture();change(bundle.files[0]);const bytes=Buffer.from(JSON.stringify(bundle));args.receipt.sha256=sha(bytes);args.receipt.size=bytes.length;const bucket=new Bucket();await assert.rejects(publishArtifact(bucket,bytes,args));assert.equal(bucket.data.size,0);}});
test('partial storage failure leaves no ready manifest and retry repairs it',async()=>{const {bytes,args}=fixture(),bucket=new Bucket();const put=bucket.put.bind(bucket);bucket.put=async(key,body)=>{if(key.endsWith('manifest.json'))throw Error('outage');return put(key,body);};await assert.rejects(publishArtifact(bucket,bytes,args),/outage/);assert.equal(bucket.data.size,1);bucket.put=put;const result=await publishArtifact(bucket,bytes,args);assert.equal(result.file_count,1);assert.equal(bucket.data.size,2);});

test('common MIME types, HEAD and static response security headers survive publication',async()=>{
 const {serve,promote}=await import('../src/serving.mjs');
 class ServingBucket extends Bucket{version=0;async put(key,body,options={}){if(options.onlyIf?.etagDoesNotMatch==='*'&&this.data.has(key))return null;this.data.set(key,Buffer.from(body));return {etag:String(++this.version)};}async head(key){const b=this.data.get(key);return b?{size:b.length}:null;}async get(key){const b=this.data.get(key);return b?{body:b,etag:String(this.version),arrayBuffer:async()=>b,text:async()=>b.toString()}:null;}}
 const types={'index.html':'text/html; charset=utf-8','site.css':'text/css; charset=utf-8','app.js':'text/javascript; charset=utf-8','app.mjs':'text/javascript; charset=utf-8','data.json':'application/json','logo.svg':'image/svg+xml','icon.png':'image/png','photo.jpg':'image/jpeg','photo.jpeg':'image/jpeg','photo.webp':'image/webp','font.woff':'font/woff','font.woff2':'font/woff2','robots.txt':'text/plain; charset=utf-8','feed.xml':'application/xml','app.wasm':'application/wasm'};
 const files=Object.entries(types).map(([name,mime])=>{const bytes=Buffer.from(name);return {path:'/'+name,mime,size:bytes.length,sha256:sha(bytes),body:bytes.toString('base64')}}),bytes=Buffer.from(JSON.stringify({format:'switchyard-static-v1',base_path:'/docs/',files})),bucket=new ServingBucket();
 const target=await publishArtifact(bucket,bytes,{siteID:'site_test1',deploymentID:'deploy_test1',basePath:'/docs/',receipt:{name:'pages-static.bundle.json',sha256:sha(bytes),size:bytes.length,source_sha:'a'.repeat(40),job_id:'pages'}});
 await promote(bucket,'n-ham','docs',target,0,'mime-cert');
 for(const [name,mime] of Object.entries(types)){const request=new Request('https://n-ham.switchyard.cx/docs/'+name,{method:'HEAD',headers:{Cookie:'switchyard_session=secret'}}),response=await serve(request,{PAGES_BUCKET:bucket});assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),mime);assert.equal(response.headers.get('Content-Length'),String(Buffer.byteLength(name)));assert.equal(response.headers.get('X-Content-Type-Options'),'nosniff');assert.equal(response.headers.get('Set-Cookie'),null);assert.equal(response.headers.get('Service-Worker-Allowed'),null);assert.equal(await response.text(),'');}
});
