import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {exportStatic} from '../src/export.mjs';import {serve,promote} from '../src/serving.mjs';
class Bucket{data=new Map();version=0;async put(k,v,o={}){const old=this.data.get(k);if(o.onlyIf?.etagDoesNotMatch==='*'&&old||o.onlyIf?.etagMatches&&o.onlyIf.etagMatches!==old?.etag)return null;const value=Buffer.from(v),record={value,size:value.length,etag:String(++this.version)};this.data.set(k,record);return record;}async get(k){const r=this.data.get(k);return r?{...r,body:r.value,text:async()=>r.value.toString()}:null;}async head(k){return this.data.get(k)||null;}}
test('real Nift builds work at owner root and dotted project prefix without rewriting',async()=>{
 for(const basePath of ['/','/foo.js/']){const root=await mkdtemp(path.join(os.tmpdir(),'pages-nift-'));try{
 const working=path.join(root,'website');for(const dir of ['.nift','content','templates','dist'])await mkdir(path.join(working,dir),{recursive:true});
 await writeFile(path.join(working,'.nift/config.json'),JSON.stringify({config:{'content-dir':'content/','content-ext':'.html','output-dir':'dist/','output-ext':'.html','default-template':'templates/template.html','build-threads':1,'incremental-mode':'modified','minify-exts':[]}}));
 await writeFile(path.join(working,'.nift/tracked.json'),JSON.stringify({tracked:[{name:'index',title:'Home',template:'templates/template.html'},{name:'nested/index',title:'Nested',template:'templates/template.html'}]}));
 await mkdir(path.join(working,'content/nested'));await writeFile(path.join(working,'content/index.html'),'<h1>Home</h1><a href="nested/">Nested</a>');await writeFile(path.join(working,'content/nested/index.html'),'<h1>Nested</h1>');await writeFile(path.join(working,'templates/template.html'),`<!doctype html><link rel="stylesheet" href="${basePath}site.css"><script type="module" src="${basePath}app.mjs"></script>@content`);
 execFileSync('nift',['build','--all'],{cwd:working,stdio:'pipe'});await writeFile(path.join(working,'dist/site.css'),'body{color:green}');await writeFile(path.join(working,'dist/app.mjs'),'window.siteReady=true;');
 const bucket=new Bucket(),result=await exportStatic({workspace:root,output:'website/dist',siteID:'site_nift1',deploymentID:'deploy_nift1',basePath,bucket});const manifest=await(await bucket.get('pages/site_nift1/deploy_nift1/manifest.json')).text();result.manifest_hash=createHash('sha256').update(manifest).digest('hex');
 await promote(bucket,'strut-labs',basePath==='/'?'/':'foo.js',result,0,'nift-build');const request=pathname=>new Request('https://strut-labs.switchyard.cx'+pathname),env={PAGES_BUCKET:bucket};
 const html=await(await serve(request(basePath),env)).text();assert.ok(html.includes(basePath+'site.css'));assert.ok(html.includes('<h1>Home</h1>'));assert.equal((await serve(request(basePath+'site.css'),env)).headers.get('Content-Type'),'text/css; charset=utf-8');assert.equal((await serve(request(basePath+'nested/'),env)).status,200);assert.equal((await serve(request(basePath+'missing'),env)).status,404);if(basePath!=='/')assert.equal((await serve(request('/site.css'),env)).status,404);
 }finally{await rm(root,{recursive:true,force:true});}}
});
