import {createHash} from 'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';import {serve,promote} from '../src/serving.mjs';
class Bucket{
 constructor(){this.data=new Map();this.version=0;}
 async get(k,options={}){const x=this.data.get(k);if(!x)return null;let body=x.value;if(options.range){body=body.slice(options.range.offset,options.range.offset+options.range.length);}return {etag:x.etag,text:async()=>x.value,body};}
 async head(k){return this.data.get(k)||null;}
 async put(k,value,options={}){const old=this.data.get(k);if(options.onlyIf?.etagMatches&&old?.etag!==options.onlyIf.etagMatches||options.onlyIf?.etagDoesNotMatch==='*'&&old)return null;const record={value,size:Buffer.byteLength(value),etag:String(++this.version)};this.data.set(k,record);return record;}
}
async function fixture(){const bucket=new Bucket();const root={site_id:'site_root1',deployment_id:'deploy_root1',base_path:'/'},docs={site_id:'site_docs1',deployment_id:'deploy_docs1',base_path:'/foo.js/'};
 for(const target of [root,docs]){const key=`pages/${target.site_id}/${target.deployment_id}/files/one`;await bucket.put(key,target.base_path==='/'?'owner content':'project content');const manifest=JSON.stringify({base_path:target.base_path,files:{'/index.html':{key,mime:'text/html; charset=utf-8',sha256:'a'.repeat(64),size:target.base_path==='/'?13:15}}});target.manifest_hash=createHash('sha256').update(manifest).digest('hex');await bucket.put(`pages/${target.site_id}/${target.deployment_id}/manifest.json`,manifest);}
 await bucket.put('pages-hosts/strut-labs.json',JSON.stringify({generation:1,root,projects:{'foo.js':docs}}));return {bucket,root,docs};}
const req=path=>new Request('https://strut-labs.switchyard.cx'+path);
test('owner and dotted project mount precedence, project 404 cannot fall through',async()=>{const {bucket}=await fixture();const env={PAGES_BUCKET:bucket};assert.equal(await (await serve(req('/'),env)).text(),'owner content');assert.equal(await (await serve(req('/foo.js/'),env)).text(),'project content');assert.equal((await serve(req('/foo.js/missing'),env)).status,404);assert.equal((await serve(req('/foo.js'),env)).status,308);assert.equal((await serve(req('/foo.js2'),env)).status,404);});
test('HEAD, ETag and range, unsafe paths',async()=>{const {bucket}=await fixture();const env={PAGES_BUCKET:bucket};assert.equal(await (await serve(new Request(req('/'),{method:'HEAD'}),env)).text(),'');assert.equal((await serve(new Request(req('/'),{headers:{'If-None-Match':'"'+'a'.repeat(64)+'"'}}),env)).status,304);const ranged=await serve(new Request(req('/'),{headers:{Range:'bytes=0-4'}}),env);assert.equal(ranged.status,206);assert.equal(await ranged.text(),'owner');assert.equal((await serve(req('/foo.js/%2fsecret'),env)).status,400);});
test('preview retains base path and has immutable identity',async()=>{const {bucket,docs}=await fixture();await bucket.put('pages-previews/preview123.json',JSON.stringify(docs));const env={PAGES_BUCKET:bucket};assert.equal((await serve(new Request('https://dpl-preview123.switchyard.cx/'),env)).status,308);assert.equal(await (await serve(new Request('https://dpl-preview123.switchyard.cx/foo.js/'),env)).text(),'project content');});
test('promotion preserves other prefixes and conflicts without changing map',async()=>{const {bucket,root,docs}=await fixture();let map=await promote(bucket,'strut-labs','foo.js',docs,1,'op-one');assert.deepEqual(map.root,root);assert.equal(map.generation,2);assert.equal((await promote(bucket,'strut-labs','foo.js',docs,1,'op-one')).generation,2);await assert.rejects(promote(bucket,'strut-labs','/',root,1,'op-two'),/conflict/);await assert.rejects(promote(bucket,'strut-labs','foo.js',{...docs,site_id:'site_other'},2,'op-three'),/another_site/);assert.equal(JSON.parse(await (await bucket.get('pages-hosts/strut-labs.json')).text()).generation,2);});

test('corrupt manifest and missing payload cannot replace production',async()=>{const {bucket,docs}=await fixture();const key='pages/site_docs1/deploy_docs1/manifest.json';await bucket.put(key,'{}');await assert.rejects(promote(bucket,'strut-labs','foo.js',docs,1,'corrupt'),/integrity/);assert.equal(JSON.parse(await (await bucket.get('pages-hosts/strut-labs.json')).text()).generation,1);});
test('concurrent promotions acknowledge exactly one map write',async()=>{const {bucket,root,docs}=await fixture();const results=await Promise.allSettled([promote(bucket,'strut-labs','/',root,1,'race-one'),promote(bucket,'strut-labs','foo.js',docs,1,'race-two')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(JSON.parse(await (await bucket.get('pages-hosts/strut-labs.json')).text()).generation,2);});
test('operation replay cannot change manifest or site identity',async()=>{const {bucket,docs}=await fixture();await promote(bucket,'strut-labs','foo.js',docs,1,'replay');await assert.rejects(promote(bucket,'strut-labs','foo.js',{...docs,manifest_hash:'b'.repeat(64)},2,'replay'),/input_conflict/);});

test('infrastructure owner names agree with application validation',async()=>{const {bucket,root}=await fixture();for(const owner of ['www','docs','app','api','admin','assets','static','pages','login','signup','sy']){await bucket.put('pages-hosts/'+owner+'.json',JSON.stringify({generation:1,root,projects:{}}));assert.equal((await serve(new Request('https://'+owner+'.switchyard.cx/'),{PAGES_BUCKET:bucket})).status,404,owner);}});
